INSERT INTO brewery_table (brewer_name, address) VALUES ("Draught House Pub and Brewery","4112 Medical Parkway Austin TX 78741");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Independence Brewing Co.","3913 Todd Lane, No. 607 Austin TX 78744");
INSERT INTO brewery_table (brewer_name, address) VALUES ("North by Northwest Restaurant and Brewery","10010 Capital Of TX Hwy N Austin TX 78759");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Uncle Billy's Brew and Que","1530 Barton Springs Road Austin TX 78704");
INSERT INTO brewery_table (brewer_name, address) VALUES ("(512) Brewing Company","407 Radam, F200 Austin TX 78745");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Black Star Co-op Pub and Brewery","7020 Easy Wind Drive, Suite 100 Austin TX 78752");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Thirsty Planet Brewing","11160 Circle Drive Austin TX 78736");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Jester King Craft Brewery","13005 Fitzhugh Rd. Austin TX 78736");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Circle Brewing Company","2340 W Braker Ln., Suite B  Austin TX 78758");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Hops and Grain Brewing","507 Calles Street Austin TX 78702");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Austin Beerworks","3009 Industrial Terrace Austin TX 78758");
INSERT INTO brewery_table (brewer_name, address) VALUES ("South Austin Brewing Company","415 E St. Elmo Rd Austin TX 78745");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Twisted X Brewing Co","3200 W Whitestone Blvd Austin TX 78613");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Adelbert's Brewery","2314 Rutland Drive, #100 Austin TX 78758");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Pinthouse Pizza","4729 Burnet Road Austin TX 78756");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Infamous Brewing Co","4602 Weletka Dr Suite #200-300 Austin TX 78734");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Austin Beer Garden Brewing Co","1305 W. Oltorf Austin TX 78704");
INSERT INTO brewery_table (brewer_name, address) VALUES ("4th Tap Brewing Co-Op","10615 Metric Blvd Austin TX 78758");
INSERT INTO brewery_table (brewer_name, address) VALUES ("NXNW South","5701 W Slaughter, Bldg. D Austin TX 78749");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Zilker Brewing Co","1701 E 6th St Austin tx 78702");
INSERT INTO brewery_table (brewer_name, address) VALUES ("St Elmo Brewing Company","440 E. St. Elmo Rd. Suite G-2 Austin TX 78745");
INSERT INTO brewery_table (brewer_name, address) VALUES ("Lazarus Brewing Co","1902 E 6th St Austin TX 78702");